### ISSUE TITLE
关于蒸馏过程的疑问

### ISSUE THREAD

**Issue by leondada** [FengHZ/KD3A#3]
某一轮内进行了如下的步骤：
--在端侧模型训练完成后记录source_domain的准确率A1
--云侧对模型进行蒸馏后，不进行联邦平均，直接测试source_domain的准确率A2
结果A2明显小于A1，按理说source的模型蒸馏过程中应该不变，所以A2应该等于A1才对

我对代码的修改很少，并且没有改动蒸馏过程，应该不会引入bug。想请教您是否我对算法理解有误？

**Comment by leondada** [comment]
检查下代码，发现了问题所在，但不确定这是代码的bug还是文章算法就是应该如此。
train.py文件中train函数里面在蒸馏阶段应该用eval()固定源域模型，否则源域模型在蒸馏阶段的迭代过程中bn层是一直在变的。但是根据我对论文的理解，教师模型的bn层似乎不用变？

**Comment by FengHZ** [comment]
Sorry for the late response. Yes your are right, we change the running mean and running var in BN to heuristically implement the BatchNorm MMD. You may find the details in appendix (BatchnormMMD). This implementation is suggested by one of the reviewers and seems difficult to understand, but it works heuristically and saves much training time. For further discussion, please contact my email fenghz@zju.edu.cn so that I can response in time. Thanks!
